package com.jder.ui.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

data class ColorPalette(
    val name: String,
    val primaryColor: Color,
    val lightScheme: ColorScheme,
    val darkScheme: ColorScheme,
)

object ColorPalettes {
  private fun createPalette(
      name: String,
      lightPrimary: Color,
      lightOnPrimary: Color,
      lightPrimaryContainer: Color,
      lightOnPrimaryContainer: Color,
      lightSecondary: Color,
      lightOnSecondary: Color,
      lightSecondaryContainer: Color,
      lightOnSecondaryContainer: Color,
      lightTertiary: Color,
      lightOnTertiary: Color,
      lightTertiaryContainer: Color,
      lightOnTertiaryContainer: Color,
      darkPrimary: Color,
      darkOnPrimary: Color,
      darkPrimaryContainer: Color,
      darkOnPrimaryContainer: Color,
      darkSecondary: Color,
      darkOnSecondary: Color,
      darkSecondaryContainer: Color,
      darkOnSecondaryContainer: Color,
      darkTertiary: Color,
      darkOnTertiary: Color,
      darkTertiaryContainer: Color,
      darkOnTertiaryContainer: Color,
  ) =
      ColorPalette(
          name = name,
          primaryColor = lightPrimary,
          lightScheme =
              lightColorScheme(
                  primary = lightPrimary,
                  onPrimary = lightOnPrimary,
                  primaryContainer = lightPrimaryContainer,
                  onPrimaryContainer = lightOnPrimaryContainer,
                  secondary = lightSecondary,
                  onSecondary = lightOnSecondary,
                  secondaryContainer = lightSecondaryContainer,
                  onSecondaryContainer = lightOnSecondaryContainer,
                  tertiary = lightTertiary,
                  onTertiary = lightOnTertiary,
                  tertiaryContainer = lightTertiaryContainer,
                  onTertiaryContainer = lightOnTertiaryContainer,
                  error = Color(0xFFB00020),
                  errorContainer = Color(0xFFFCD8DF),
                  onError = Color(0xFFFFFFFF),
                  onErrorContainer = Color(0xFF8C0009),
                  background = Color(0xFFFAFAFA),
                  onBackground = Color(0xFF1A1A1A),
                  surface = Color(0xFFFFFFFF),
                  onSurface = Color(0xFF1A1A1A),
                  surfaceVariant = Color(0xFFE0E0E0),
                  onSurfaceVariant = Color(0xFF424242),
                  outline = Color(0xFF757575),
                  inverseOnSurface = Color(0xFFF5F5F5),
                  inverseSurface = Color(0xFF2F2F2F),
                  inversePrimary = darkPrimary,
              ),
          darkScheme =
              darkColorScheme(
                  primary = darkPrimary,
                  onPrimary = darkOnPrimary,
                  primaryContainer = darkPrimaryContainer,
                  onPrimaryContainer = darkOnPrimaryContainer,
                  secondary = darkSecondary,
                  onSecondary = darkOnSecondary,
                  secondaryContainer = darkSecondaryContainer,
                  onSecondaryContainer = darkOnSecondaryContainer,
                  tertiary = darkTertiary,
                  onTertiary = darkOnTertiary,
                  tertiaryContainer = darkTertiaryContainer,
                  onTertiaryContainer = darkOnTertiaryContainer,
                  error = Color(0xFFCF6679),
                  errorContainer = Color(0xFF93000A),
                  onError = Color(0xFF690005),
                  onErrorContainer = Color(0xFFFCD8DF),
                  background = Color(0xFF121212),
                  onBackground = Color(0xFFE0E0E0),
                  surface = Color(0xFF1E1E1E),
                  onSurface = Color(0xFFE0E0E0),
                  surfaceVariant = Color(0xFF424242),
                  onSurfaceVariant = Color(0xFFBDBDBD),
                  outline = Color(0xFF8D8D8D),
                  inverseOnSurface = Color(0xFF1A1A1A),
                  inverseSurface = Color(0xFFE0E0E0),
                  inversePrimary = lightPrimary,
              ),
      )

  val Blue =
      createPalette(
          name = "Blue",
          lightPrimary = Color(0xFF2196F3),
          lightOnPrimary = Color(0xFFFFFFFF),
          lightPrimaryContainer = Color(0xFFBBDEFB),
          lightOnPrimaryContainer = Color(0xFF0D47A1),
          lightSecondary = Color(0xFF03A9F4),
          lightOnSecondary = Color(0xFFFFFFFF),
          lightSecondaryContainer = Color(0xFFB3E5FC),
          lightOnSecondaryContainer = Color(0xFF01579B),
          lightTertiary = Color(0xFF009688),
          lightOnTertiary = Color(0xFFFFFFFF),
          lightTertiaryContainer = Color(0xFFB2DFDB),
          lightOnTertiaryContainer = Color(0xFF004D40),
          darkPrimary = Color(0xFF90CAF9),
          darkOnPrimary = Color(0xFF0D47A1),
          darkPrimaryContainer = Color(0xFF1565C0),
          darkOnPrimaryContainer = Color(0xFFBBDEFB),
          darkSecondary = Color(0xFF81D4FA),
          darkOnSecondary = Color(0xFF01579B),
          darkSecondaryContainer = Color(0xFF0277BD),
          darkOnSecondaryContainer = Color(0xFFB3E5FC),
          darkTertiary = Color(0xFF80CBC4),
          darkOnTertiary = Color(0xFF004D40),
          darkTertiaryContainer = Color(0xFF00695C),
          darkOnTertiaryContainer = Color(0xFFB2DFDB),
      )
  val Red =
      createPalette(
          name = "Red",
          lightPrimary = Color(0xFFF44336),
          lightOnPrimary = Color(0xFFFFFFFF),
          lightPrimaryContainer = Color(0xFFFFCDD2),
          lightOnPrimaryContainer = Color(0xFFB71C1C),
          lightSecondary = Color(0xFFE91E63),
          lightOnSecondary = Color(0xFFFFFFFF),
          lightSecondaryContainer = Color(0xFFF8BBD0),
          lightOnSecondaryContainer = Color(0xFF880E4F),
          lightTertiary = Color(0xFFFF5722),
          lightOnTertiary = Color(0xFFFFFFFF),
          lightTertiaryContainer = Color(0xFFFFCCBC),
          lightOnTertiaryContainer = Color(0xFFBF360C),
          darkPrimary = Color(0xFFEF9A9A),
          darkOnPrimary = Color(0xFFB71C1C),
          darkPrimaryContainer = Color(0xFFC62828),
          darkOnPrimaryContainer = Color(0xFFFFCDD2),
          darkSecondary = Color(0xFFF48FB1),
          darkOnSecondary = Color(0xFF880E4F),
          darkSecondaryContainer = Color(0xFFC2185B),
          darkOnSecondaryContainer = Color(0xFFF8BBD0),
          darkTertiary = Color(0xFFFFAB91),
          darkOnTertiary = Color(0xFFBF360C),
          darkTertiaryContainer = Color(0xFFE64A19),
          darkOnTertiaryContainer = Color(0xFFFFCCBC),
      )
  val Green =
      createPalette(
          name = "Green",
          lightPrimary = Color(0xFF4CAF50),
          lightOnPrimary = Color(0xFFFFFFFF),
          lightPrimaryContainer = Color(0xFFC8E6C9),
          lightOnPrimaryContainer = Color(0xFF1B5E20),
          lightSecondary = Color(0xFF8BC34A),
          lightOnSecondary = Color(0xFFFFFFFF),
          lightSecondaryContainer = Color(0xFFDCEDC8),
          lightOnSecondaryContainer = Color(0xFF33691E),
          lightTertiary = Color(0xFF009688),
          lightOnTertiary = Color(0xFFFFFFFF),
          lightTertiaryContainer = Color(0xFFB2DFDB),
          lightOnTertiaryContainer = Color(0xFF004D40),
          darkPrimary = Color(0xFFA5D6A7),
          darkOnPrimary = Color(0xFF1B5E20),
          darkPrimaryContainer = Color(0xFF388E3C),
          darkOnPrimaryContainer = Color(0xFFC8E6C9),
          darkSecondary = Color(0xFFC5E1A5),
          darkOnSecondary = Color(0xFF33691E),
          darkSecondaryContainer = Color(0xFF689F38),
          darkOnSecondaryContainer = Color(0xFFDCEDC8),
          darkTertiary = Color(0xFF80CBC4),
          darkOnTertiary = Color(0xFF004D40),
          darkTertiaryContainer = Color(0xFF00695C),
          darkOnTertiaryContainer = Color(0xFFB2DFDB),
      )
  val Purple =
      createPalette(
          name = "Purple",
          lightPrimary = Color(0xFF9C27B0),
          lightOnPrimary = Color(0xFFFFFFFF),
          lightPrimaryContainer = Color(0xFFE1BEE7),
          lightOnPrimaryContainer = Color(0xFF4A148C),
          lightSecondary = Color(0xFF673AB7),
          lightOnSecondary = Color(0xFFFFFFFF),
          lightSecondaryContainer = Color(0xFFD1C4E9),
          lightOnSecondaryContainer = Color(0xFF311B92),
          lightTertiary = Color(0xFF3F51B5),
          lightOnTertiary = Color(0xFFFFFFFF),
          lightTertiaryContainer = Color(0xFFC5CAE9),
          lightOnTertiaryContainer = Color(0xFF1A237E),
          darkPrimary = Color(0xFFCE93D8),
          darkOnPrimary = Color(0xFF4A148C),
          darkPrimaryContainer = Color(0xFF7B1FA2),
          darkOnPrimaryContainer = Color(0xFFE1BEE7),
          darkSecondary = Color(0xFFB39DDB),
          darkOnSecondary = Color(0xFF311B92),
          darkSecondaryContainer = Color(0xFF512DA8),
          darkOnSecondaryContainer = Color(0xFFD1C4E9),
          darkTertiary = Color(0xFF9FA8DA),
          darkOnTertiary = Color(0xFF1A237E),
          darkTertiaryContainer = Color(0xFF303F9F),
          darkOnTertiaryContainer = Color(0xFFC5CAE9),
      )
  val Orange =
      createPalette(
          name = "Orange",
          lightPrimary = Color(0xFFFF9800),
          lightOnPrimary = Color(0xFFFFFFFF),
          lightPrimaryContainer = Color(0xFFFFE0B2),
          lightOnPrimaryContainer = Color(0xFFE65100),
          lightSecondary = Color(0xFFFF5722),
          lightOnSecondary = Color(0xFFFFFFFF),
          lightSecondaryContainer = Color(0xFFFFCCBC),
          lightOnSecondaryContainer = Color(0xFFBF360C),
          lightTertiary = Color(0xFFFF6F00),
          lightOnTertiary = Color(0xFFFFFFFF),
          lightTertiaryContainer = Color(0xFFFFD180),
          lightOnTertiaryContainer = Color(0xFFE65100),
          darkPrimary = Color(0xFFFFCC80),
          darkOnPrimary = Color(0xFFE65100),
          darkPrimaryContainer = Color(0xFFF57C00),
          darkOnPrimaryContainer = Color(0xFFFFE0B2),
          darkSecondary = Color(0xFFFFAB91),
          darkOnSecondary = Color(0xFFBF360C),
          darkSecondaryContainer = Color(0xFFE64A19),
          darkOnSecondaryContainer = Color(0xFFFFCCBC),
          darkTertiary = Color(0xFFFFD180),
          darkOnTertiary = Color(0xFFE65100),
          darkTertiaryContainer = Color(0xFFF57C00),
          darkOnTertiaryContainer = Color(0xFFFFD180),
      )
  val Teal =
      createPalette(
          name = "Teal",
          lightPrimary = Color(0xFF009688),
          lightOnPrimary = Color(0xFFFFFFFF),
          lightPrimaryContainer = Color(0xFFB2DFDB),
          lightOnPrimaryContainer = Color(0xFF004D40),
          lightSecondary = Color(0xFF00BCD4),
          lightOnSecondary = Color(0xFFFFFFFF),
          lightSecondaryContainer = Color(0xFFB2EBF2),
          lightOnSecondaryContainer = Color(0xFF006064),
          lightTertiary = Color(0xFF26A69A),
          lightOnTertiary = Color(0xFFFFFFFF),
          lightTertiaryContainer = Color(0xFFB2DFDB),
          lightOnTertiaryContainer = Color(0xFF004D40),
          darkPrimary = Color(0xFF80CBC4),
          darkOnPrimary = Color(0xFF004D40),
          darkPrimaryContainer = Color(0xFF00695C),
          darkOnPrimaryContainer = Color(0xFFB2DFDB),
          darkSecondary = Color(0xFF80DEEA),
          darkOnSecondary = Color(0xFF006064),
          darkSecondaryContainer = Color(0xFF00838F),
          darkOnSecondaryContainer = Color(0xFFB2EBF2),
          darkTertiary = Color(0xFF80CBC4),
          darkOnTertiary = Color(0xFF004D40),
          darkTertiaryContainer = Color(0xFF00695C),
          darkOnTertiaryContainer = Color(0xFFB2DFDB),
      )
  val Indigo =
      createPalette(
          name = "Indigo",
          lightPrimary = Color(0xFF3F51B5),
          lightOnPrimary = Color(0xFFFFFFFF),
          lightPrimaryContainer = Color(0xFFC5CAE9),
          lightOnPrimaryContainer = Color(0xFF1A237E),
          lightSecondary = Color(0xFF5C6BC0),
          lightOnSecondary = Color(0xFFFFFFFF),
          lightSecondaryContainer = Color(0xFFD1C4E9),
          lightOnSecondaryContainer = Color(0xFF311B92),
          lightTertiary = Color(0xFF2196F3),
          lightOnTertiary = Color(0xFFFFFFFF),
          lightTertiaryContainer = Color(0xFFBBDEFB),
          lightOnTertiaryContainer = Color(0xFF0D47A1),
          darkPrimary = Color(0xFF9FA8DA),
          darkOnPrimary = Color(0xFF1A237E),
          darkPrimaryContainer = Color(0xFF303F9F),
          darkOnPrimaryContainer = Color(0xFFC5CAE9),
          darkSecondary = Color(0xFF7986CB),
          darkOnSecondary = Color(0xFF311B92),
          darkSecondaryContainer = Color(0xFF512DA8),
          darkOnSecondaryContainer = Color(0xFFD1C4E9),
          darkTertiary = Color(0xFF90CAF9),
          darkOnTertiary = Color(0xFF0D47A1),
          darkTertiaryContainer = Color(0xFF1565C0),
          darkOnTertiaryContainer = Color(0xFFBBDEFB),
      )
  val Pink =
      createPalette(
          name = "Pink",
          lightPrimary = Color(0xFFE91E63),
          lightOnPrimary = Color(0xFFFFFFFF),
          lightPrimaryContainer = Color(0xFFF8BBD0),
          lightOnPrimaryContainer = Color(0xFF880E4F),
          lightSecondary = Color(0xFFEC407A),
          lightOnSecondary = Color(0xFFFFFFFF),
          lightSecondaryContainer = Color(0xFFF8BBD0),
          lightOnSecondaryContainer = Color(0xFF880E4F),
          lightTertiary = Color(0xFF9C27B0),
          lightOnTertiary = Color(0xFFFFFFFF),
          lightTertiaryContainer = Color(0xFFE1BEE7),
          lightOnTertiaryContainer = Color(0xFF4A148C),
          darkPrimary = Color(0xFFF48FB1),
          darkOnPrimary = Color(0xFF880E4F),
          darkPrimaryContainer = Color(0xFFC2185B),
          darkOnPrimaryContainer = Color(0xFFF8BBD0),
          darkSecondary = Color(0xFFF48FB1),
          darkOnSecondary = Color(0xFF880E4F),
          darkSecondaryContainer = Color(0xFFC2185B),
          darkOnSecondaryContainer = Color(0xFFF8BBD0),
          darkTertiary = Color(0xFFCE93D8),
          darkOnTertiary = Color(0xFF4A148C),
          darkTertiaryContainer = Color(0xFF7B1FA2),
          darkOnTertiaryContainer = Color(0xFFE1BEE7),
      )
  val Cyan =
      createPalette(
          name = "Cyan",
          lightPrimary = Color(0xFF00BCD4),
          lightOnPrimary = Color(0xFFFFFFFF),
          lightPrimaryContainer = Color(0xFFB2EBF2),
          lightOnPrimaryContainer = Color(0xFF006064),
          lightSecondary = Color(0xFF00ACC1),
          lightOnSecondary = Color(0xFFFFFFFF),
          lightSecondaryContainer = Color(0xFFB2EBF2),
          lightOnSecondaryContainer = Color(0xFF006064),
          lightTertiary = Color(0xFF0097A7),
          lightOnTertiary = Color(0xFFFFFFFF),
          lightTertiaryContainer = Color(0xFFB2EBF2),
          lightOnTertiaryContainer = Color(0xFF006064),
          darkPrimary = Color(0xFF80DEEA),
          darkOnPrimary = Color(0xFF006064),
          darkPrimaryContainer = Color(0xFF00838F),
          darkOnPrimaryContainer = Color(0xFFB2EBF2),
          darkSecondary = Color(0xFF80DEEA),
          darkOnSecondary = Color(0xFF006064),
          darkSecondaryContainer = Color(0xFF00838F),
          darkOnSecondaryContainer = Color(0xFFB2EBF2),
          darkTertiary = Color(0xFF80DEEA),
          darkOnTertiary = Color(0xFF006064),
          darkTertiaryContainer = Color(0xFF00838F),
          darkOnTertiaryContainer = Color(0xFFB2EBF2),
      )
  val Amber =
      createPalette(
          name = "Amber",
          lightPrimary = Color(0xFFFFC107),
          lightOnPrimary = Color(0xFF000000),
          lightPrimaryContainer = Color(0xFFFFECB3),
          lightOnPrimaryContainer = Color(0xFFFF6F00),
          lightSecondary = Color(0xFFFFB300),
          lightOnSecondary = Color(0xFF000000),
          lightSecondaryContainer = Color(0xFFFFE082),
          lightOnSecondaryContainer = Color(0xFFFF6F00),
          lightTertiary = Color(0xFFFF9800),
          lightOnTertiary = Color(0xFFFFFFFF),
          lightTertiaryContainer = Color(0xFFFFE0B2),
          lightOnTertiaryContainer = Color(0xFFE65100),
          darkPrimary = Color(0xFFFFD54F),
          darkOnPrimary = Color(0xFFFF6F00),
          darkPrimaryContainer = Color(0xFFFFA000),
          darkOnPrimaryContainer = Color(0xFFFFECB3),
          darkSecondary = Color(0xFFFFD54F),
          darkOnSecondary = Color(0xFFFF6F00),
          darkSecondaryContainer = Color(0xFFFFA000),
          darkOnSecondaryContainer = Color(0xFFFFE082),
          darkTertiary = Color(0xFFFFCC80),
          darkOnTertiary = Color(0xFFE65100),
          darkTertiaryContainer = Color(0xFFF57C00),
          darkOnTertiaryContainer = Color(0xFFFFE0B2),
      )
  val DeepPurple =
      createPalette(
          name = "Deep Purple",
          lightPrimary = Color(0xFF673AB7),
          lightOnPrimary = Color(0xFFFFFFFF),
          lightPrimaryContainer = Color(0xFFD1C4E9),
          lightOnPrimaryContainer = Color(0xFF311B92),
          lightSecondary = Color(0xFF7E57C2),
          lightOnSecondary = Color(0xFFFFFFFF),
          lightSecondaryContainer = Color(0xFFD1C4E9),
          lightOnSecondaryContainer = Color(0xFF311B92),
          lightTertiary = Color(0xFF9C27B0),
          lightOnTertiary = Color(0xFFFFFFFF),
          lightTertiaryContainer = Color(0xFFE1BEE7),
          lightOnTertiaryContainer = Color(0xFF4A148C),
          darkPrimary = Color(0xFFB39DDB),
          darkOnPrimary = Color(0xFF311B92),
          darkPrimaryContainer = Color(0xFF512DA8),
          darkOnPrimaryContainer = Color(0xFFD1C4E9),
          darkSecondary = Color(0xFFB39DDB),
          darkOnSecondary = Color(0xFF311B92),
          darkSecondaryContainer = Color(0xFF512DA8),
          darkOnSecondaryContainer = Color(0xFFD1C4E9),
          darkTertiary = Color(0xFFCE93D8),
          darkOnTertiary = Color(0xFF4A148C),
          darkTertiaryContainer = Color(0xFF7B1FA2),
          darkOnTertiaryContainer = Color(0xFFE1BEE7),
      )
  val LightGreen =
      createPalette(
          name = "Light Green",
          lightPrimary = Color(0xFF8BC34A),
          lightOnPrimary = Color(0xFF000000),
          lightPrimaryContainer = Color(0xFFDCEDC8),
          lightOnPrimaryContainer = Color(0xFF33691E),
          lightSecondary = Color(0xFF9CCC65),
          lightOnSecondary = Color(0xFF000000),
          lightSecondaryContainer = Color(0xFFDCEDC8),
          lightOnSecondaryContainer = Color(0xFF33691E),
          lightTertiary = Color(0xFF4CAF50),
          lightOnTertiary = Color(0xFFFFFFFF),
          lightTertiaryContainer = Color(0xFFC8E6C9),
          lightOnTertiaryContainer = Color(0xFF1B5E20),
          darkPrimary = Color(0xFFC5E1A5),
          darkOnPrimary = Color(0xFF33691E),
          darkPrimaryContainer = Color(0xFF689F38),
          darkOnPrimaryContainer = Color(0xFFDCEDC8),
          darkSecondary = Color(0xFFC5E1A5),
          darkOnSecondary = Color(0xFF33691E),
          darkSecondaryContainer = Color(0xFF689F38),
          darkOnSecondaryContainer = Color(0xFFDCEDC8),
          darkTertiary = Color(0xFFA5D6A7),
          darkOnTertiary = Color(0xFF1B5E20),
          darkTertiaryContainer = Color(0xFF388E3C),
          darkOnTertiaryContainer = Color(0xFFC8E6C9),
      )
  val Lime =
      createPalette(
          name = "Lime",
          lightPrimary = Color(0xFFCDDC39),
          lightOnPrimary = Color(0xFF000000),
          lightPrimaryContainer = Color(0xFFF0F4C3),
          lightOnPrimaryContainer = Color(0xFF827717),
          lightSecondary = Color(0xFFD4E157),
          lightOnSecondary = Color(0xFF000000),
          lightSecondaryContainer = Color(0xFFF0F4C3),
          lightOnSecondaryContainer = Color(0xFF827717),
          lightTertiary = Color(0xFF8BC34A),
          lightOnTertiary = Color(0xFF000000),
          lightTertiaryContainer = Color(0xFFDCEDC8),
          lightOnTertiaryContainer = Color(0xFF33691E),
          darkPrimary = Color(0xFFE6EE9C),
          darkOnPrimary = Color(0xFF827717),
          darkPrimaryContainer = Color(0xFFAFB42B),
          darkOnPrimaryContainer = Color(0xFFF0F4C3),
          darkSecondary = Color(0xFFE6EE9C),
          darkOnSecondary = Color(0xFF827717),
          darkSecondaryContainer = Color(0xFFAFB42B),
          darkOnSecondaryContainer = Color(0xFFF0F4C3),
          darkTertiary = Color(0xFFC5E1A5),
          darkOnTertiary = Color(0xFF33691E),
          darkTertiaryContainer = Color(0xFF689F38),
          darkOnTertiaryContainer = Color(0xFFDCEDC8),
      )
  val Yellow =
      createPalette(
          name = "Yellow",
          lightPrimary = Color(0xFFFFEB3B),
          lightOnPrimary = Color(0xFF000000),
          lightPrimaryContainer = Color(0xFFFFF9C4),
          lightOnPrimaryContainer = Color(0xFFF57F17),
          lightSecondary = Color(0xFFFFD54F),
          lightOnSecondary = Color(0xFF000000),
          lightSecondaryContainer = Color(0xFFFFF9C4),
          lightOnSecondaryContainer = Color(0xFFF57F17),
          lightTertiary = Color(0xFFFFC107),
          lightOnTertiary = Color(0xFF000000),
          lightTertiaryContainer = Color(0xFFFFECB3),
          lightOnTertiaryContainer = Color(0xFFFF6F00),
          darkPrimary = Color(0xFFFFF176),
          darkOnPrimary = Color(0xFFF57F17),
          darkPrimaryContainer = Color(0xFFFBC02D),
          darkOnPrimaryContainer = Color(0xFFFFF9C4),
          darkSecondary = Color(0xFFFFF176),
          darkOnSecondary = Color(0xFFF57F17),
          darkSecondaryContainer = Color(0xFFFBC02D),
          darkOnSecondaryContainer = Color(0xFFFFF9C4),
          darkTertiary = Color(0xFFFFD54F),
          darkOnTertiary = Color(0xFFFF6F00),
          darkTertiaryContainer = Color(0xFFFFA000),
          darkOnTertiaryContainer = Color(0xFFFFECB3),
      )
  val DeepOrange =
      createPalette(
          name = "Deep Orange",
          lightPrimary = Color(0xFFFF5722),
          lightOnPrimary = Color(0xFFFFFFFF),
          lightPrimaryContainer = Color(0xFFFFCCBC),
          lightOnPrimaryContainer = Color(0xFFBF360C),
          lightSecondary = Color(0xFFFF7043),
          lightOnSecondary = Color(0xFFFFFFFF),
          lightSecondaryContainer = Color(0xFFFFCCBC),
          lightOnSecondaryContainer = Color(0xFFBF360C),
          lightTertiary = Color(0xFFF44336),
          lightOnTertiary = Color(0xFFFFFFFF),
          lightTertiaryContainer = Color(0xFFFFCDD2),
          lightOnTertiaryContainer = Color(0xFFB71C1C),
          darkPrimary = Color(0xFFFFAB91),
          darkOnPrimary = Color(0xFFBF360C),
          darkPrimaryContainer = Color(0xFFE64A19),
          darkOnPrimaryContainer = Color(0xFFFFCCBC),
          darkSecondary = Color(0xFFFFAB91),
          darkOnSecondary = Color(0xFFBF360C),
          darkSecondaryContainer = Color(0xFFE64A19),
          darkOnSecondaryContainer = Color(0xFFFFCCBC),
          darkTertiary = Color(0xFFEF9A9A),
          darkOnTertiary = Color(0xFFB71C1C),
          darkTertiaryContainer = Color(0xFFC62828),
          darkOnTertiaryContainer = Color(0xFFFFCDD2),
      )
  val Brown =
      createPalette(
          name = "Brown",
          lightPrimary = Color(0xFF795548),
          lightOnPrimary = Color(0xFFFFFFFF),
          lightPrimaryContainer = Color(0xFFD7CCC8),
          lightOnPrimaryContainer = Color(0xFF3E2723),
          lightSecondary = Color(0xFF8D6E63),
          lightOnSecondary = Color(0xFFFFFFFF),
          lightSecondaryContainer = Color(0xFFD7CCC8),
          lightOnSecondaryContainer = Color(0xFF3E2723),
          lightTertiary = Color(0xFFA1887F),
          lightOnTertiary = Color(0xFF000000),
          lightTertiaryContainer = Color(0xFFD7CCC8),
          lightOnTertiaryContainer = Color(0xFF3E2723),
          darkPrimary = Color(0xFFBCAAA4),
          darkOnPrimary = Color(0xFF3E2723),
          darkPrimaryContainer = Color(0xFF5D4037),
          darkOnPrimaryContainer = Color(0xFFD7CCC8),
          darkSecondary = Color(0xFFBCAAA4),
          darkOnSecondary = Color(0xFF3E2723),
          darkSecondaryContainer = Color(0xFF5D4037),
          darkOnSecondaryContainer = Color(0xFFD7CCC8),
          darkTertiary = Color(0xFFBCAAA4),
          darkOnTertiary = Color(0xFF3E2723),
          darkTertiaryContainer = Color(0xFF5D4037),
          darkOnTertiaryContainer = Color(0xFFD7CCC8),
      )
  val LightBlue =
      createPalette(
          name = "Light Blue",
          lightPrimary = Color(0xFF03A9F4),
          lightOnPrimary = Color(0xFFFFFFFF),
          lightPrimaryContainer = Color(0xFFB3E5FC),
          lightOnPrimaryContainer = Color(0xFF01579B),
          lightSecondary = Color(0xFF29B6F6),
          lightOnSecondary = Color(0xFFFFFFFF),
          lightSecondaryContainer = Color(0xFFB3E5FC),
          lightOnSecondaryContainer = Color(0xFF01579B),
          lightTertiary = Color(0xFF0288D1),
          lightOnTertiary = Color(0xFFFFFFFF),
          lightTertiaryContainer = Color(0xFFB3E5FC),
          lightOnTertiaryContainer = Color(0xFF01579B),
          darkPrimary = Color(0xFF81D4FA),
          darkOnPrimary = Color(0xFF01579B),
          darkPrimaryContainer = Color(0xFF0277BD),
          darkOnPrimaryContainer = Color(0xFFB3E5FC),
          darkSecondary = Color(0xFF81D4FA),
          darkOnSecondary = Color(0xFF01579B),
          darkSecondaryContainer = Color(0xFF0277BD),
          darkOnSecondaryContainer = Color(0xFFB3E5FC),
          darkTertiary = Color(0xFF81D4FA),
          darkOnTertiary = Color(0xFF01579B),
          darkTertiaryContainer = Color(0xFF0277BD),
          darkOnTertiaryContainer = Color(0xFFB3E5FC),
      )
  val Gray =
      createPalette(
          name = "Gray",
          lightPrimary = Color(0xFF9E9E9E),
          lightOnPrimary = Color(0xFFFFFFFF),
          lightPrimaryContainer = Color(0xFFEEEEEE),
          lightOnPrimaryContainer = Color(0xFF212121),
          lightSecondary = Color(0xFF757575),
          lightOnSecondary = Color(0xFFFFFFFF),
          lightSecondaryContainer = Color(0xFFE0E0E0),
          lightOnSecondaryContainer = Color(0xFF212121),
          lightTertiary = Color(0xFFBDBDBD),
          lightOnTertiary = Color(0xFF000000),
          lightTertiaryContainer = Color(0xFFF5F5F5),
          lightOnTertiaryContainer = Color(0xFF424242),
          darkPrimary = Color(0xFFBDBDBD),
          darkOnPrimary = Color(0xFF212121),
          darkPrimaryContainer = Color(0xFF616161),
          darkOnPrimaryContainer = Color(0xFFF5F5F5),
          darkSecondary = Color(0xFFE0E0E0),
          darkOnSecondary = Color(0xFF212121),
          darkSecondaryContainer = Color(0xFF757575),
          darkOnSecondaryContainer = Color(0xFFFAFAFA),
          darkTertiary = Color(0xFF9E9E9E),
          darkOnTertiary = Color(0xFF000000),
          darkTertiaryContainer = Color(0xFF424242),
          darkOnTertiaryContainer = Color(0xFFEEEEEE),
      )
  val BlueGray =
      createPalette(
          name = "Blue Gray",
          lightPrimary = Color(0xFF607D8B),
          lightOnPrimary = Color(0xFFFFFFFF),
          lightPrimaryContainer = Color(0xFFCFD8DC),
          lightOnPrimaryContainer = Color(0xFF263238),
          lightSecondary = Color(0xFF78909C),
          lightOnSecondary = Color(0xFFFFFFFF),
          lightSecondaryContainer = Color(0xFFB0BEC5),
          lightOnSecondaryContainer = Color(0xFF263238),
          lightTertiary = Color(0xFF90A4AE),
          lightOnTertiary = Color(0xFF000000),
          lightTertiaryContainer = Color(0xFFECEFF1),
          lightOnTertiaryContainer = Color(0xFF37474F),
          darkPrimary = Color(0xFFB0BEC5),
          darkOnPrimary = Color(0xFF263238),
          darkPrimaryContainer = Color(0xFF455A64),
          darkOnPrimaryContainer = Color(0xFFCFD8DC),
          darkSecondary = Color(0xFF90A4AE),
          darkOnSecondary = Color(0xFF263238),
          darkSecondaryContainer = Color(0xFF546E7A),
          darkOnSecondaryContainer = Color(0xFFB0BEC5),
          darkTertiary = Color(0xFF78909C),
          darkOnTertiary = Color(0xFF000000),
          darkTertiaryContainer = Color(0xFF37474F),
          darkOnTertiaryContainer = Color(0xFFECEFF1),
      )
  val BlackAndWhite =
      createPalette(
          name = "Black & White",
          lightPrimary = Color(0xFF000000),
          lightOnPrimary = Color(0xFFFFFFFF),
          lightPrimaryContainer = Color(0xFF424242),
          lightOnPrimaryContainer = Color(0xFFFFFFFF),
          lightSecondary = Color(0xFF212121),
          lightOnSecondary = Color(0xFFFFFFFF),
          lightSecondaryContainer = Color(0xFF616161),
          lightOnSecondaryContainer = Color(0xFFFFFFFF),
          lightTertiary = Color(0xFFFFFFFF),
          lightOnTertiary = Color(0xFF000000),
          lightTertiaryContainer = Color(0xFFF5F5F5),
          lightOnTertiaryContainer = Color(0xFF212121),
          darkPrimary = Color(0xFFFFFFFF),
          darkOnPrimary = Color(0xFF000000),
          darkPrimaryContainer = Color(0xFFBDBDBD),
          darkOnPrimaryContainer = Color(0xFF000000),
          darkSecondary = Color(0xFFF5F5F5),
          darkOnSecondary = Color(0xFF000000),
          darkSecondaryContainer = Color(0xFF9E9E9E),
          darkOnSecondaryContainer = Color(0xFF000000),
          darkTertiary = Color(0xFF424242),
          darkOnTertiary = Color(0xFFFFFFFF),
          darkTertiaryContainer = Color(0xFF212121),
          darkOnTertiaryContainer = Color(0xFFF5F5F5),
      )
  val allPalettes =
      listOf(
          Red,
          Pink,
          Purple,
          DeepPurple,
          Indigo,
          Blue,
          LightBlue,
          Cyan,
          Teal,
          Green,
          LightGreen,
          Lime,
          Yellow,
          Amber,
          Orange,
          DeepOrange,
          Brown,
          Gray,
          BlueGray,
          BlackAndWhite,
      )
}
